### ISSUE TITLE
Forcasting

### ISSUE THREAD

**Issue by NicoCodes-Lab** [gboehl/econpizza#11]
Hi Gregor, 
Sorry for the new interruption. I was wondering if there is an example to do some forcasting on real data on the econpizza package. 
Thank you very much in advance!

**Comment by gboehl** [comment]
Hi Nico,

There is no forecasing. This is a simulation framework which does not include tools for structural econometrics.

Cheers, 
Gregor

**Comment by NicoCodes-Lab** [comment]
Thank you Gregor for the quick and accurate response. 
I ask you given your experience in the field: if I build a linear DSGE model for forcasting do I lose much "accuracy" compared to a nonlinear one? Or maybe it depends a lot on the equations used?

**Comment by gboehl** [comment]
As always: it depends. But for any standard model (that is, standard production function, utility etc.) linearization is not too problematic. Also, nonlinear estimations are very hard, so don't do it unless you really know what you are doing.
