### ISSUE TITLE
Parameter on persistence of shock in `dsge.yml`

### ISSUE THREAD

**Issue by andkound98** [gboehl/econpizza#7]
Hey, this [parameter here](https://github.com/gboehl/econpizza/blob/a2eb10af7a435f110f20fc0c9fb2be4bb66b2265/econpizza/examples/dsge.yml#L88) in the `dsge.yml` is the persistence of the risk premium shock, right?

**Comment by gboehl** [comment]
Absolutely! 

Thanks for pointing this out. 

Fixed with [1375318](https://github.com/gboehl/econpizza/commit/1375318149e0ccdb5c86f00dce8c2af71a124e0f).
