### ISSUE TITLE
Marginal Costs in the NKPC in the One-Asset HANK Example

### ISSUE THREAD

**Issue by andkound98** [gboehl/econpizza#8]
Hey, I was wondering whether in the example of the [one-asset HANK model](https://github.com/gboehl/econpizza/blob/master/econpizza/examples/hank_with_comments.yml) the [marginal costs in the Phillips Curve](https://github.com/gboehl/econpizza/blob/e58002488f04233a6ba9217e981f3d4828d51a3f/econpizza/examples/hank_with_comments.yml#L92C52-L92C54) should be specified as $\frac{w_t}{z}$ rather than only $w_t$? If so, then we would have $mc_t = \frac{w_t}{z}$ and in steady state: $mc_{ss} = \frac{\theta - 1}{\theta}$ and $w_{ss} = mc_{ss}*z$, correct? Changing this had for me only a small effect anyway, but perhaps for some nevertheless important (whenever $z \ne 1$).

**Comment by gboehl** [comment]
Yes, absolutely!

Thanks for pointing this out, should be more relevant for technology shocks. 

Are you willing to make a PR?

**Comment by andkound98** [comment]
Yes, will do! Thank you.

**Comment by gboehl** [comment]
Wonderful. Thanks for #10 !
